#ifndef PROGRAMA_H
#define PROGRAMA_H

enum class PROGRAMA
{COZINHA_SAUDAVEL, MEU_PRATO, DESONGELACAO, AQUECIMENTO, MICROONDAS, GRILL,
COMBINADO, ELIMINACAO_CHEIROS, ECO, PRATO_GIRATORIO, COZINHA_RAPIDA};

#endif // ESTADOMICROONDAS_H
